CoreAndFood/Controllers/FoodController.cs
using CoreAndFood.Data.Models;
using CoreAndFood.Data.Models.Dto;
using CoreAndFood.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using X.PagedList;

namespace CoreAndFood.Controllers
{
    public class FoodController : Controller
    {
        FoodRepository foodRepository = new FoodRepository();
        Context c = new Context();
        public IActionResult Index(int page=1 )
        {
            
            //return View(foodRepository.TList());
            var result = (from p in c.Foods
                          join d in c.Categories
                          on p.CategoryID equals d.CategoryID
                          select new FoodIViewDto
                          {
                              FoodID = p.FoodID,
                              Name = p.Name,
                              Description = p.Description,
                              Price = p.Price,
                              ImageURL = p.ImageURL,
                              Stock = p.Stock,
                              CategoryNameView = d.CategoryName
                          }).ToList();
            return View(result.ToPagedList(page,5));
        }
        [HttpGet]
        public IActionResult FoodAdd()
        {
            List<SelectListItem> CategoryList=(from x in c.Categories.ToList()
                                               select new SelectListItem
                                               {
                                                 Text=x.CategoryName,
                                                 Value=x.CategoryID.ToString()
                                               }).ToList();
            ViewBag.cl = CategoryList;
            return View();
        }
        [HttpPost]
        public IActionResult FoodAdd(Food p)
        {
            foodRepository.TAdd(p);
            return RedirectToAction("Index");
        }
        public IActionResult FoodDelete(int id)
        {
            foodRepository.TDelete(new Food { FoodID=id});
            return RedirectToAction("Index");
        }
        public IActionResult FoodGet(int id)
        {
            var x=foodRepository.TGet(id);
            List<SelectListItem> CategoryList = (from y in c.Categories.ToList()
                                                 select new SelectListItem
                                                 {
                                                     Text = y.CategoryName,
                                                     Value = y.CategoryID.ToString()
                                                 }).ToList();
            ViewBag.cl = CategoryList;
            Food p = new Food()
            {
                FoodID=x.FoodID,
                CategoryID = x.CategoryID,
                Name = x.Name,
                Price = x.Price,
                Stock = x.Stock,
                Description = x.Description,
                ImageURL=x.ImageURL
            };
            return View(p);
        }
        public IActionResult FoodUpdate(Food p)
        {
            var x = foodRepository.TGet(p.FoodID);
            x.Name = p.Name;
            x.Price = p.Price;
            x.Stock = p.Stock;
            x.Description = p.Description;
            x.ImageURL = p.ImageURL;
            x.CategoryID = p.CategoryID;
            foodRepository.TUpdate(x);
            return RedirectToAction("Index");
        }
       

    }
}

CoreAndFood/Views/Food/FoodAdd.cshtml
@model CoreAndFood.Data.Models.Food
@{
    ViewData["Title"] = "FoodAdd";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food Add Page</h2>
<br />
@using(Html.BeginForm("FoodAdd","Food",FormMethod.Post))
{
    @Html.LabelFor(x=>x.Name)
    @Html.TextBoxFor(x=>x.Name,new {@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Stock)
    @Html.TextBoxFor(x=>x.Stock,new {@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Price)
    @Html.TextBoxFor(x=>x.Price,new {@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.ImageURL)
    @Html.TextBoxFor(x=>x.ImageURL,new {@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Category)
    @Html.DropDownListFor(x=>x.CategoryID,(List<SelectListItem>)ViewBag.cl,new{@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Description)
    @Html.TextAreaFor(x=>x.Description,new {@class="form-control"})
    <br />
    
    <button class="btn btn-primary">Save</button>
}

CoreAndFood/Views/Food/FoodGet.cshtml
@model CoreAndFood.Data.Models.Food
@{
    ViewData["Title"] = "FoodGet";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food Update Page</h2>
<br />
@using(Html.BeginForm("FoodUpdate","Food",FormMethod.Post))
{
    @Html.LabelFor(x=>x.FoodID)
    @Html.TextBoxFor(x=>x.FoodID,new {@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Name)
    @Html.TextBoxFor(x=>x.Name,new {@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Stock)
    @Html.TextBoxFor(x=>x.Stock,new {@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Price)
    @Html.TextBoxFor(x=>x.Price,new {@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.ImageURL)
    @Html.TextBoxFor(x=>x.ImageURL,new {@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Category)
    @*@Html.TextBoxFor(x=>x.Category,new {@class="form-control"})*@
    @Html.DropDownListFor(x=>x.CategoryID,(List<SelectListItem>)ViewBag.cl,new{@class="form-control"})
    <br />
    @Html.LabelFor(x=>x.Description)
    @Html.TextAreaFor(x=>x.Description,new {@class="form-control"})
    <br />
    
    <button class="btn btn-warning">Update</button>
}

CoreAndFood/Views/Food/Index.cshtml
@using X.PagedList;
@using X.PagedList.Mvc.Core;
@model IPagedList<CoreAndFood.Data.Models.Dto.FoodIViewDto>
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Food List</h2>
<br />

<table class="table table-bordered">
    <tr>
        <th>ID</th>
        <th>Food Name</th>
        <th>Price</th>
        <th>Stock</th>
        <th>Category Name</th>
        <th>Food Description</th>
        <th>Delete</th>
        <th>Update</th>
       @* <th>Details</th>*@
    </tr>
    @foreach (var x in Model)
    {
        <tr>
            <td>@x.FoodID</td>
            <td>@x.Name</td>
            <td>@x.Price</td>
            <td>@x.Stock</td>
            <td>@x.CategoryNameView</td>
            <td>@x.Description</td>
            <td><a href="/Food/FoodDelete/@x.FoodID" class="btn btn-danger">Delete</a>
            <td><a href="/Food/FoodGet/@x.FoodID" class="btn btn-success">Update</a>
           @* <td><a href="#" class="btn btn-info">Details</a>   *@     
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model,page=>Url.Action("Index",new{page}))
<a href="/Food/FoodAdd/" class="btn btn-primary">New Food</a>